#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["Microservices.PlatformService/Microservices.PlatformService.csproj", "Microservices.PlatformService/"]
COPY ["Microservices/Microservices.csproj", "Microservices/"]
RUN dotnet restore "Microservices.Platform/Microservices.PlatformService.csproj"
COPY . .
WORKDIR "/src/Microservices.Platform"
RUN dotnet build "Microservices.PlatformService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Microservices.PlatformService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Microservices.PlatformService.dll"]