#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["KuzmichInc.Microservices.Platform/KuzmichInc.Microservices.PlatformService.csproj", "KuzmichInc.Microservices.Platform/"]
COPY ["KuzmichInc.Microservices/KuzmichInc.Microservices.csproj", "KuzmichInc.Microservices/"]
RUN dotnet restore "KuzmichInc.Microservices.Platform/KuzmichInc.Microservices.PlatformService.csproj"
COPY . .
WORKDIR "/src/KuzmichInc.Microservices.Platform"
RUN dotnet build "KuzmichInc.Microservices.PlatformService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "KuzmichInc.Microservices.PlatformService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KuzmichInc.Microservices.PlatformService.dll"]